/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type ExternalArticle = {
  _id: string;
  _type: "externalArticle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  publication: string;
  publishedAt: string;
  url: string;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  publishedAt: string;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  body: BlockContent;
  seo?: Seo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: string;
  attribution?: string;
  source?: string;
};

export type Audience = {
  _id: string;
  _type: "audience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  challenge: string;
  offer: string;
  order: number;
};

export type Pillar = {
  _id: string;
  _type: "pillar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  oneLiner: string;
  description?: string;
  order: number;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  intro?: string;
  formHeading?: string;
  successMessage?: string;
  seo?: Seo;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  name?: string;
  role?: string;
  headshot?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  story?: BlockContent;
  highlightsHeading?: string;
  highlights?: Array<string>;
  civicHeading?: string;
  civicBody?: string;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type WhoWeWorkWithPage = {
  _id: string;
  _type: "whoWeWorkWithPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  intro?: string;
  seo?: Seo;
};

export type WhatWeDoPage = {
  _id: string;
  _type: "whatWeDoPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  intro?: string;
  howWeWorkHeading?: string;
  howWeWorkBody?: BlockContent;
  seo?: Seo;
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeading: string;
  heroKicker?: string;
  heroCtaLabel?: string;
  credibilityHeading?: string;
  credibilityItems?: Array<string>;
  pillarsHeading?: string;
  pillarsIntro?: string;
  testimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  thinkingHeading?: string;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  wordmark: string;
  positioningStatement: string;
  contactEmail: string;
  linkedinUrl?: string;
  location?: string;
  navItems?: Array<{
    label: string;
    href: string;
    _type: "navItem";
    _key: string;
  }>;
  ctaLabel?: string;
  footerCta?: string;
  footerLegal?: string;
  ga4MeasurementId?: string;
  defaultSeo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TagReference
  | ExternalArticle
  | Post
  | SanityImageAssetReference
  | Seo
  | BlockContent
  | Slug
  | Tag
  | Testimonial
  | Audience
  | Pillar
  | ContactPage
  | AboutPage
  | SanityImageCrop
  | SanityImageHotspot
  | WhoWeWorkWithPage
  | WhatWeDoPage
  | TestimonialReference
  | HomePage
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    wordmark,    positioningStatement,    contactEmail,    linkedinUrl,    location,    navItems[]{ label, href },    ctaLabel,    footerCta,    footerLegal,    ga4MeasurementId,    defaultSeo { metaTitle, metaDescription, ogImage }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  wordmark: string;
  positioningStatement: string;
  contactEmail: string;
  linkedinUrl: string | null;
  location: string | null;
  navItems: Array<{
    label: string;
    href: string;
  }> | null;
  ctaLabel: string | null;
  footerCta: string | null;
  footerLegal: string | null;
  ga4MeasurementId: string | null;
  defaultSeo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0]{    heroKicker,    heroHeading,    heroCtaLabel,    credibilityHeading,    credibilityItems,    pillarsHeading,    pillarsIntro,    thinkingHeading,    "testimonials": testimonials[]->{ _id, quote, attribution, source },      seo { metaTitle, metaDescription, ogImage }  }
export type HOME_PAGE_QUERY_RESULT = {
  heroKicker: string | null;
  heroHeading: string;
  heroCtaLabel: string | null;
  credibilityHeading: string | null;
  credibilityItems: Array<string> | null;
  pillarsHeading: string | null;
  pillarsIntro: string | null;
  thinkingHeading: string | null;
  testimonials: Array<{
    _id: string;
    quote: string;
    attribution: string | null;
    source: string | null;
  }> | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PILLARS_QUERY
// Query: *[_type == "pillar"] | order(order asc){    _id, title, "slug": slug.current, oneLiner, description, order  }
export type PILLARS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  oneLiner: string;
  description: string | null;
  order: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: AUDIENCES_QUERY
// Query: *[_type == "audience"] | order(order asc){    _id, name, challenge, offer, order  }
export type AUDIENCES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  challenge: string;
  offer: string;
  order: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: WHAT_WE_DO_QUERY
// Query: *[_type == "whatWeDoPage"][0]{    title, intro, howWeWorkHeading, howWeWorkBody,   seo { metaTitle, metaDescription, ogImage }  }
export type WHAT_WE_DO_QUERY_RESULT = {
  title: string;
  intro: string | null;
  howWeWorkHeading: string | null;
  howWeWorkBody: BlockContent | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: WHO_WE_WORK_WITH_QUERY
// Query: *[_type == "whoWeWorkWithPage"][0]{    title, intro,   seo { metaTitle, metaDescription, ogImage }  }
export type WHO_WE_WORK_WITH_QUERY_RESULT = {
  title: string;
  intro: string | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"][0]{    title, name, role,    headshot{ ..., "alt": alt },    story,    highlightsHeading, highlights,    civicHeading, civicBody,      seo { metaTitle, metaDescription, ogImage }  }
export type ABOUT_PAGE_QUERY_RESULT = {
  title: string;
  name: string | null;
  role: string | null;
  headshot: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  story: BlockContent | null;
  highlightsHeading: string | null;
  highlights: Array<string> | null;
  civicHeading: string | null;
  civicBody: string | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage"][0]{    title, intro, formHeading, successMessage,   seo { metaTitle, metaDescription, ogImage }  }
export type CONTACT_PAGE_QUERY_RESULT = {
  title: string;
  intro: string | null;
  formHeading: string | null;
  successMessage: string | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: THINKING_FEED_QUERY
// Query: *[    (_type == "post" || _type == "externalArticle") &&    ($tag == "" || $tag in tags[]->slug.current)  ] | order(coalesce(publishedAt, _createdAt) desc){    _id,    _type,    title,    "slug": slug.current,    excerpt,    publication,    url,    publishedAt,    "tags": tags[]->{ title, "slug": slug.current }  }
export type THINKING_FEED_QUERY_RESULT = Array<
  | {
      _id: string;
      _type: "externalArticle";
      title: string;
      slug: null;
      excerpt: null;
      publication: string;
      url: string;
      publishedAt: string;
      tags: Array<{
        title: string;
        slug: string;
      }> | null;
    }
  | {
      _id: string;
      _type: "post";
      title: string;
      slug: string;
      excerpt: string;
      publication: null;
      url: null;
      publishedAt: string;
      tags: Array<{
        title: string;
        slug: string;
      }> | null;
    }
>;

// Source: src/sanity/lib/queries.ts
// Variable: LATEST_THINKING_QUERY
// Query: *[_type == "post" || _type == "externalArticle"]    | order(coalesce(publishedAt, _createdAt) desc)[0...3]{    _id,    _type,    title,    "slug": slug.current,    excerpt,    publication,    url,    publishedAt  }
export type LATEST_THINKING_QUERY_RESULT = Array<
  | {
      _id: string;
      _type: "externalArticle";
      title: string;
      slug: null;
      excerpt: null;
      publication: string;
      url: string;
      publishedAt: string;
    }
  | {
      _id: string;
      _type: "post";
      title: string;
      slug: string;
      excerpt: string;
      publication: null;
      url: null;
      publishedAt: string;
    }
>;

// Source: src/sanity/lib/queries.ts
// Variable: TAGS_QUERY
// Query: *[_type == "tag"] | order(title asc){ _id, title, "slug": slug.current }
export type TAGS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    body,    "tags": tags[]->{ title, "slug": slug.current },      seo { metaTitle, metaDescription, ogImage }  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  body: BlockContent;
  tags: Array<{
    title: string;
    slug: string;
  }> | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0]{\n    wordmark,\n    positioningStatement,\n    contactEmail,\n    linkedinUrl,\n    location,\n    navItems[]{ label, href },\n    ctaLabel,\n    footerCta,\n    footerLegal,\n    ga4MeasurementId,\n    defaultSeo { metaTitle, metaDescription, ogImage }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "homePage"][0]{\n    heroKicker,\n    heroHeading,\n    heroCtaLabel,\n    credibilityHeading,\n    credibilityItems,\n    pillarsHeading,\n    pillarsIntro,\n    thinkingHeading,\n    "testimonials": testimonials[]->{ _id, quote, attribution, source },\n    \n  seo { metaTitle, metaDescription, ogImage }\n\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "pillar"] | order(order asc){\n    _id, title, "slug": slug.current, oneLiner, description, order\n  }\n': PILLARS_QUERY_RESULT;
    '\n  *[_type == "audience"] | order(order asc){\n    _id, name, challenge, offer, order\n  }\n': AUDIENCES_QUERY_RESULT;
    '\n  *[_type == "whatWeDoPage"][0]{\n    title, intro, howWeWorkHeading, howWeWorkBody, \n  seo { metaTitle, metaDescription, ogImage }\n\n  }\n': WHAT_WE_DO_QUERY_RESULT;
    '\n  *[_type == "whoWeWorkWithPage"][0]{\n    title, intro, \n  seo { metaTitle, metaDescription, ogImage }\n\n  }\n': WHO_WE_WORK_WITH_QUERY_RESULT;
    '\n  *[_type == "aboutPage"][0]{\n    title, name, role,\n    headshot{ ..., "alt": alt },\n    story,\n    highlightsHeading, highlights,\n    civicHeading, civicBody,\n    \n  seo { metaTitle, metaDescription, ogImage }\n\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_type == "contactPage"][0]{\n    title, intro, formHeading, successMessage, \n  seo { metaTitle, metaDescription, ogImage }\n\n  }\n': CONTACT_PAGE_QUERY_RESULT;
    '\n  *[\n    (_type == "post" || _type == "externalArticle") &&\n    ($tag == "" || $tag in tags[]->slug.current)\n  ] | order(coalesce(publishedAt, _createdAt) desc){\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publication,\n    url,\n    publishedAt,\n    "tags": tags[]->{ title, "slug": slug.current }\n  }\n': THINKING_FEED_QUERY_RESULT;
    '\n  *[_type == "post" || _type == "externalArticle"]\n    | order(coalesce(publishedAt, _createdAt) desc)[0...3]{\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publication,\n    url,\n    publishedAt\n  }\n': LATEST_THINKING_QUERY_RESULT;
    '\n  *[_type == "tag"] | order(title asc){ _id, title, "slug": slug.current }\n': TAGS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    body,\n    "tags": tags[]->{ title, "slug": slug.current },\n    \n  seo { metaTitle, metaDescription, ogImage }\n\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]{ "slug": slug.current }\n': POST_SLUGS_QUERY_RESULT;
  }
}
