import { defineArrayMember, defineField, defineType } from "sanity";

export const homePageType = defineType({
  name: "homePage",
  title: "Home",
  type: "document",
  groups: [
    { name: "hero", title: "Hero" },
    { name: "sections", title: "Sections" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "heroHeading",
      title: "Hero heading",
      type: "text",
      rows: 3,
      group: "hero",
      description: "The positioning statement. Must land with authority in under five seconds.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroKicker",
      title: "Hero kicker",
      type: "string",
      group: "hero",
      description: "Small line above the heading, e.g. “Technology & AI Policy Advisory”.",
    }),
    defineField({
      name: "heroSubline",
      title: "Hero sub-line",
      type: "text",
      rows: 2,
      group: "hero",
      description: "Optional line under the heading, e.g. the Nairobi-to-Brussels framing.",
    }),
    defineField({
      name: "heroCtaLabel",
      title: "Hero CTA label",
      type: "string",
      group: "hero",
      initialValue: "Get in touch",
    }),
    defineField({
      name: "positioningBody",
      title: "Positioning statement",
      type: "blockContent",
      group: "sections",
      description: "The longer statement below the fold, before the credibility strip.",
    }),
    defineField({
      name: "credibilityHeading",
      title: "Credibility strip heading",
      type: "string",
      group: "sections",
      description: "E.g. “Experience drawn from”.",
    }),
    defineField({
      name: "credibilityItems",
      title: "Credibility references",
      type: "array",
      group: "sections",
      of: [defineArrayMember({ type: "string" })],
      description: "Named organisations, e.g. TikTok, Google, Office of the President of Kenya.",
    }),
    defineField({
      name: "pillarsHeading",
      title: "Service pillars heading",
      type: "string",
      group: "sections",
      initialValue: "What we do",
    }),
    defineField({
      name: "pillarsIntro",
      title: "Service pillars intro",
      type: "text",
      rows: 2,
      group: "sections",
    }),
    defineField({
      name: "pillarsCtaLabel",
      title: "Service pillars CTA label",
      type: "string",
      group: "sections",
      initialValue: "See all services",
      description: "Links to /what-we-do.",
    }),
    defineField({
      name: "audienceHeading",
      title: "Who we work with heading",
      type: "string",
      group: "sections",
      initialValue: "Who we work with",
    }),
    defineField({
      name: "audienceBody",
      title: "Who we work with summary",
      type: "text",
      rows: 3,
      group: "sections",
    }),
    defineField({
      name: "audienceCtaLabel",
      title: "Who we work with CTA label",
      type: "string",
      group: "sections",
      initialValue: "Learn more",
      description: "Links to /who-we-work-with.",
    }),
    defineField({
      name: "aboutTeaserBody",
      title: "About teaser",
      type: "text",
      rows: 3,
      group: "sections",
      description: "Sits under the credibility strip.",
    }),
    defineField({
      name: "aboutCtaLabel",
      title: "About CTA label",
      type: "string",
      group: "sections",
      initialValue: "About Mwenda",
      description: "Links to /about.",
    }),
    defineField({
      name: "testimonials",
      title: "Social proof",
      type: "array",
      group: "sections",
      of: [defineArrayMember({ type: "reference", to: [{ type: "testimonial" }] })],
      description: "One or two testimonials or pull quotes.",
    }),
    defineField({
      name: "thinkingHeading",
      title: "Latest thinking heading",
      type: "string",
      group: "sections",
      initialValue: "Latest thinking",
      description: "The three most recent articles are pulled in automatically.",
    }),
    defineField({
      name: "thinkingIntro",
      title: "Latest thinking intro",
      type: "text",
      rows: 2,
      group: "sections",
    }),
    defineField({
      name: "thinkingCtaLabel",
      title: "Latest thinking CTA label",
      type: "string",
      group: "sections",
      initialValue: "Read our latest thinking",
      description: "Links to /thinking.",
    }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "seo" }),
  ],
  preview: {
    prepare: () => ({ title: "Home" }),
  },
});
